import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

class TestAssetLoader extends AssetLoader {
  const TestAssetLoader();

  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) async {
    return {
      "routeNotFound": "Page not found",
      "home": "Home",
      "workouts": "Workouts",
      "profile": "Profile",
      "chat": "Chat",
      "next": "Next",
      "back": "Back",
      "getStarted": "Get Started",
      "skip": "Skip",
      "emailRequired": "Email is required",
      "emailInvalid": "Please enter a valid email",
      "email": "Email",
      "enterYourEmail": "Enter your email",
      "emailVerification": "Email verification",
      "pleaseEnterYourEmailAssociated":
          "Please enter the email associated with your account",
      "pleaseEnterYourCode": "Please enter your code",
      "didntReceiveCode": "Didn't receive the code?",
      "resend": "Resend",
      "passwordRequired": "Password is required",
      "passwordWeak": "Password is too weak",
      "confirmPasswordRequired": "Please confirm your password",
      "passwordDoNotMatch": "Passwords do not match",
      "password": "Password",
      "forgetPassword": "Forgot password?",
      "confirm": "Confirm",
      "resetPassword": "Reset password",
      "newPassword": "New password",
      "enterYourPassword": "Enter your password",
      "enterPassword": "Enter password",
      "confirmPassword": "Confirm password",
      "otpEmpty": "Please enter the code",
      "otpInvalid": "Invalid code",
      "otpLength": "Code must be 4 digits",
      "noInternetConnection": "No internet connection",
      "connectionTimeout": "Connection timed out",
      "requestCancelled": "Request was cancelled",
      "badCertificate": "Security certificate error",
      "somethingWentWrong": "Something went wrong",
      "login": "Login",
      "register": "Register",
      "loggedInSuccessfully": "Logged in successfully",
      "enterYourEmailLabel": "Enter Your Email",
      "forgetPasswordTitle": "Forget Password",
      "sendOtp": "Sent OTP",
      "otpCodeLabel": "OTP CODE",
      "enterYourOtpCheckYourEmail": "Enter Your OTP Check Your Email",
      "resendCode": "Resend Code?",
      "makeSure8CharsOrMore": "Make Sure Its 8 Characters Or More",
      "createNewPasswordTitle": "Create New Password",
      "doneButton": "Done",
      "passwordChangedSuccessfully": "Password changed successfully",
      "fullBody": "Full Body",
      "noWorkoutsFound": "No workouts found",
      "exercises": "Exercises",
      "language": "language",
      "selectLanguage": "Select Language",
      "English": "English",
      "Arabic": "Arabic",
      "couldNotLaunchLink": "Could not launch link",
      "noProfileDataAvailable": "No profile data available",
      "editProfile": "Edit Profile",
      "changePassword": "Change Password",
      "security": "Security",
      "privacyPolicy": "Privacy Policy",
      "help": "Help",
      "logout": "Logout",
      "areYouSureYouWantToLogout": "Are you sure you want to logout?",
      "no": "No",
      "yes": "Yes"
    };
  }
}
